"""
Lens Feedback Component.

Renders analytical feedback, summary statistics, and visual indicators
generated by active lenses into designated Streamlit container placeholders.
"""

import logging
from typing import Optional
import pandas as pd
import streamlit as st
from streamlit.delta_generator import DeltaGenerator

from lenses.lens_registry import get_lens_module

logger = logging.getLogger(__name__)


def render_lens_feedback(
    placeholder: Optional[DeltaGenerator],
    active_lens: str,
    lens_df: Optional[pd.DataFrame],
) -> None:
    """
    Renders analytical feedback provided by the active lens into a UI placeholder.

    Parameters
    ----------
    placeholder : Optional[DeltaGenerator]
        Streamlit container placeholder where feedback UI elements will be attached.
    active_lens : str
        Identifier of the active analytical lens (e.g., 'Preference', 'Diversity').
    lens_df : Optional[pd.DataFrame]
        DataFrame resulting from the lens transformation.
    """
    if placeholder is None or lens_df is None or lens_df.empty:
        return

    if active_lens == "None" or not active_lens:
        return

    lens_module = get_lens_module(active_lens)

    if lens_module is None:
        return

    if hasattr(lens_module, "render_feedback") and callable(
        lens_module.render_feedback
    ):
        try:
            with placeholder.container():
                lens_module.render_feedback(lens_df)
        except Exception as e:
            logger.error(
                f"Error rendering feedback for lens '{active_lens}': {str(e)}"
            )
            placeholder.error(
                f"Failed to display feedback for '{active_lens}': {str(e)}"
            )