"""
Lens Feedback Component (ui/lens_feedback.py)

Renders analytical feedback, summary statistics, and visual indicators
generated by active lenses into designated Streamlit containers.
"""

import logging
from typing import Optional

import pandas as pd
import streamlit as st
from streamlit.delta_generator import DeltaGenerator

# Import the new unified interface
from lenses import get_lens

logger = logging.getLogger(__name__)


def render_lens_feedback(
    placeholder: Optional[DeltaGenerator],
    active_lens: str,
    lens_df: Optional[pd.DataFrame],
) -> None:
    """
    Renders analytical feedback provided by the active lens into a UI placeholder.

    Parameters
    ----------
    placeholder : Optional[DeltaGenerator]
        Streamlit container placeholder where feedback UI elements will be attached.
    active_lens : str
        Identifier key of the active analytical lens (e.g., 'topsis', 'kmeans', 'consensus').
    lens_df : Optional[pd.DataFrame]
        DataFrame resulting from the lens transformation.
    """
    if placeholder is None or lens_df is None or lens_df.empty:
        return

    if not active_lens or active_lens.strip().lower() == "none":
        return

    # Retrieve the lens instance from the current catalog
    lens_instance = get_lens(active_lens)

    if lens_instance is None:
        return

    try:
        with placeholder.container():
            # Check if the lens implements its own feedback rendering method
            if hasattr(lens_instance, "render_feedback") and callable(
                getattr(lens_instance, "render_feedback")
            ):
                lens_instance.render_feedback(lens_df)
            else:
                # Default generic feedback
                st.caption(f"📊 Lens Summary: **{active_lens.title()}**")
                st.metric("Resulting Solutions", len(lens_df))

    except Exception as e:
        logger.error("Error rendering feedback for lens '%s': %s", active_lens, str(e))
        placeholder.error(f"Failed to display metrics for '{active_lens}': {str(e)}")