"""
Lens Feedback Component (ui/lens_feedback.py)

Renders analytical feedback, summary statistics, and visual indicators
generated by active lenses into designated Streamlit containers.
"""

import logging
from typing import Optional

import pandas as pd
import streamlit as st
from streamlit.delta_generator import DeltaGenerator

# Usamos la nueva interfaz unificada
from lenses import get_lens

logger = logging.getLogger(__name__)


def render_lens_feedback(
    placeholder: Optional[DeltaGenerator],
    active_lens: str,
    lens_df: Optional[pd.DataFrame],
) -> None:
    """
    Renders analytical feedback provided by the active lens into a UI placeholder.

    Parameters
    ----------
    placeholder : Optional[DeltaGenerator]
        Streamlit container placeholder where feedback UI elements will be attached.
    active_lens : str
        Identifier key of the active analytical lens (e.g., 'topsis', 'kmeans', 'consensus').
    lens_df : Optional[pd.DataFrame]
        DataFrame resulting from the lens transformation.
    """
    if placeholder is None or lens_df is None or lens_df.empty:
        return

    if not active_lens or active_lens.strip().lower() == "none":
        return

    # Obtener la instancia de la lente desde el catálogo actual
    lens_instance = get_lens(active_lens)

    if lens_instance is None:
        return

    try:
        with placeholder.container():
            # Si la lente implementa su propio método de renderizado de métricas/feedback
            if hasattr(lens_instance, "render_feedback") and callable(
                getattr(lens_instance, "render_feedback")
            ):
                lens_instance.render_feedback(lens_df)
            else:
                # Feedback genérico por defecto
                st.caption(f"📊 Resumen de Lente: **{active_lens.title()}**")
                st.metric("Soluciones resultantes", len(lens_df))

    except Exception as e:
        logger.error("Error rendering feedback for lens '%s': %s", active_lens, str(e))
        placeholder.error(f"Error al mostrar métricas de '{active_lens}': {str(e)}")